//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Culinary_Guide.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Culinary_Guide.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About App 的本地化字符串。
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Culinary Guide v1.0
        ///
        ///Explore nearby restaurants and enjoy delicious life! 的本地化字符串。
        /// </summary>
        public static string AboutAppContent {
            get {
                return ResourceManager.GetString("AboutAppContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accuracy 的本地化字符串。
        /// </summary>
        public static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        public static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Culinary Guide 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse History 的本地化字符串。
        /// </summary>
        public static string BrowseHistory {
            get {
                return ResourceManager.GetString("BrowseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse History 的本地化字符串。
        /// </summary>
        public static string BrowseHistoryCount {
            get {
                return ResourceManager.GetString("BrowseHistoryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot get current location 的本地化字符串。
        /// </summary>
        public static string CannotGetLocation {
            get {
                return ResourceManager.GetString("CannotGetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beijing Cuisine 的本地化字符串。
        /// </summary>
        public static string Cuisine_Beijing {
            get {
                return ResourceManager.GetString("Cuisine_Beijing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cantonese Cuisine 的本地化字符串。
        /// </summary>
        public static string Cuisine_Cantonese {
            get {
                return ResourceManager.GetString("Cuisine_Cantonese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hunan Cuisine 的本地化字符串。
        /// </summary>
        public static string Cuisine_Hunan {
            get {
                return ResourceManager.GetString("Cuisine_Hunan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shandong Cuisine 的本地化字符串。
        /// </summary>
        public static string Cuisine_Shandong {
            get {
                return ResourceManager.GetString("Cuisine_Shandong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sichuan Cuisine 的本地化字符串。
        /// </summary>
        public static string Cuisine_Sichuan {
            get {
                return ResourceManager.GetString("Cuisine_Sichuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Western Cuisine 的本地化字符串。
        /// </summary>
        public static string Cuisine_Western {
            get {
                return ResourceManager.GetString("Cuisine_Western", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zhejiang Cuisine 的本地化字符串。
        /// </summary>
        public static string Cuisine_Zhejiang {
            get {
                return ResourceManager.GetString("Cuisine_Zhejiang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Location 的本地化字符串。
        /// </summary>
        public static string CurrentLocation {
            get {
                return ResourceManager.GetString("CurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explore food, enjoy life 的本地化字符串。
        /// </summary>
        public static string DefaultBio {
            get {
                return ResourceManager.GetString("DefaultBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Food Lover 的本地化字符串。
        /// </summary>
        public static string DefaultNickname {
            get {
                return ResourceManager.GetString("DefaultNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feature under development... 的本地化字符串。
        /// </summary>
        public static string Developing {
            get {
                return ResourceManager.GetString("Developing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter your review: 的本地化字符串。
        /// </summary>
        public static string EnterReview {
            get {
                return ResourceManager.GetString("EnterReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explore Nearby 的本地化字符串。
        /// </summary>
        public static string ExploreTitle {
            get {
                return ResourceManager.GetString("ExploreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favorite Reminder 的本地化字符串。
        /// </summary>
        public static string FavoriteNotification {
            get {
                return ResourceManager.GetString("FavoriteNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your favorite restaurant has new promotions 的本地化字符串。
        /// </summary>
        public static string FavoriteNotificationContent {
            get {
                return ResourceManager.GetString("FavoriteNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Favorites 的本地化字符串。
        /// </summary>
        public static string FavoritesTitle {
            get {
                return ResourceManager.GetString("FavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get location 的本地化字符串。
        /// </summary>
        public static string GetLocationFailed {
            get {
                return ResourceManager.GetString("GetLocationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting location... 的本地化字符串。
        /// </summary>
        public static string GettingLocation {
            get {
                return ResourceManager.GetString("GettingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discover restaurants on Home! 的本地化字符串。
        /// </summary>
        public static string GoDiscover {
            get {
                return ResourceManager.GetString("GoDiscover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latitude 的本地化字符串。
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load failed: 的本地化字符串。
        /// </summary>
        public static string LoadFailed {
            get {
                return ResourceManager.GetString("LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beijing Guomao 的本地化字符串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Location permission required to get your position 的本地化字符串。
        /// </summary>
        public static string LocationPermissionRequired {
            get {
                return ResourceManager.GetString("LocationPermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Longitude 的本地化字符串。
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 meters 的本地化字符串。
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Favorites 的本地化字符串。
        /// </summary>
        public static string MyFavoritesCount {
            get {
                return ResourceManager.GetString("MyFavoritesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Location 的本地化字符串。
        /// </summary>
        public static string MyLocation {
            get {
                return ResourceManager.GetString("MyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Feature Available 的本地化字符串。
        /// </summary>
        public static string NewFeatureNotification {
            get {
                return ResourceManager.GetString("NewFeatureNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map feature is now available, come explore nearby restaurants! 的本地化字符串。
        /// </summary>
        public static string NewFeatureNotificationContent {
            get {
                return ResourceManager.GetString("NewFeatureNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No browse history 的本地化字符串。
        /// </summary>
        public static string NoBrowseHistory {
            get {
                return ResourceManager.GetString("NoBrowseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No favorite restaurants yet 的本地化字符串。
        /// </summary>
        public static string NoFavorites {
            get {
                return ResourceManager.GetString("NoFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No nearby restaurants 的本地化字符串。
        /// </summary>
        public static string NoNearbyRestaurants {
            get {
                return ResourceManager.GetString("NoNearbyRestaurants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No new notifications 的本地化字符串。
        /// </summary>
        public static string NoNotifications {
            get {
                return ResourceManager.GetString("NoNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notification Settings 的本地化字符串。
        /// </summary>
        public static string NotificationSettings {
            get {
                return ResourceManager.GetString("NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notifications 的本地化字符串。
        /// </summary>
        public static string NotificationsTitle {
            get {
                return ResourceManager.GetString("NotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opening Hours 的本地化字符串。
        /// </summary>
        public static string OpeningHoursLabel {
            get {
                return ResourceManager.GetString("OpeningHoursLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone 的本地化字符串。
        /// </summary>
        public static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Privacy Settings 的本地化字符串。
        /// </summary>
        public static string PrivacySettings {
            get {
                return ResourceManager.GetString("PrivacySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile 的本地化字符串。
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rating 的本地化字符串。
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 restaurants 的本地化字符串。
        /// </summary>
        public static string RestaurantCount {
            get {
                return ResourceManager.GetString("RestaurantCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} reviews 的本地化字符串。
        /// </summary>
        public static string ReviewCountFormat {
            get {
                return ResourceManager.GetString("ReviewCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} reviews · Tap to view 的本地化字符串。
        /// </summary>
        public static string ReviewCountTapFormat {
            get {
                return ResourceManager.GetString("ReviewCountTapFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 reviews · Tap to view 的本地化字符串。
        /// </summary>
        public static string ReviewsCount {
            get {
                return ResourceManager.GetString("ReviewsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Review submitted! 的本地化字符串。
        /// </summary>
        public static string ReviewSubmitted {
            get {
                return ResourceManager.GetString("ReviewSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search restaurants or cuisine... 的本地化字符串。
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distance 的本地化字符串。
        /// </summary>
        public static string SortByDistance {
            get {
                return ResourceManager.GetString("SortByDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Popular 的本地化字符串。
        /// </summary>
        public static string SortByPopular {
            get {
                return ResourceManager.GetString("SortByPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rating 的本地化字符串。
        /// </summary>
        public static string SortByRating {
            get {
                return ResourceManager.GetString("SortByRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explore 的本地化字符串。
        /// </summary>
        public static string TabExplore {
            get {
                return ResourceManager.GetString("TabExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favorites 的本地化字符串。
        /// </summary>
        public static string TabFavorites {
            get {
                return ResourceManager.GetString("TabFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string TabHome {
            get {
                return ResourceManager.GetString("TabHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Reviews 的本地化字符串。
        /// </summary>
        public static string UserReviewsLabel {
            get {
                return ResourceManager.GetString("UserReviewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Profile 的本地化字符串。
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nickname 的本地化字符串。
        /// </summary>
        public static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bio 的本地化字符串。
        /// </summary>
        public static string Bio {
            get {
                return ResourceManager.GetString("Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Avatar 的本地化字符串。
        /// </summary>
        public static string ChangeAvatar {
            get {
                return ResourceManager.GetString("ChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Take Photo 的本地化字符串。
        /// </summary>
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose from Gallery 的本地化字符串。
        /// </summary>
        public static string ChooseFromGallery {
            get {
                return ResourceManager.GetString("ChooseFromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter nickname 的本地化字符串。
        /// </summary>
        public static string NicknamePlaceholder {
            get {
                return ResourceManager.GetString("NicknamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tell us about yourself... 的本地化字符串。
        /// </summary>
        public static string BioPlaceholder {
            get {
                return ResourceManager.GetString("BioPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Profile updated! 的本地化字符串。
        /// </summary>
        public static string ProfileUpdated {
            get {
                return ResourceManager.GetString("ProfileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to change avatar 的本地化字符串。
        /// </summary>
        public static string TapToChangeAvatar {
            get {
                return ResourceManager.GetString("TapToChangeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View more 的本地化字符串。
        /// </summary>
        public static string ViewMore {
            get {
                return ResourceManager.GetString("ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to Culinary Guide 的本地化字符串。
        /// </summary>
        public static string WelcomeNotification {
            get {
                return ResourceManager.GetString("WelcomeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Explore nearby restaurants and enjoy delicious life! 的本地化字符串。
        /// </summary>
        public static string WelcomeNotificationContent {
            get {
                return ResourceManager.GetString("WelcomeNotificationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 what eat today？ 的本地化字符串。
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write Review 的本地化字符串。
        /// </summary>
        public static string WriteReview {
            get {
                return ResourceManager.GetString("WriteReview", resourceCulture);
            }
        }
    }
}
